var ebolaMapData = [
    {
        "hc_name": "CME Nyakunde (Bunia)",
        "hc_type": "Ebola Treatment Center",
        "country": "DRC",
        "province": "Ituri",
        "zone": "Bunia",
        "lat": 1.53867,
        "lon": 30.24895,
        "cases": 150,
        "deaths": 30,
        "recoveries": 5,
        "cfr": 20.0,
        "date": "2026-06-12"
    },
    {
        "hc_name": "Mongbwalu General Referral Hospital",
        "hc_type": "Ebola Treatment Center",
        "country": "DRC",
        "province": "Ituri",
        "zone": "Mongbwalu",
        "lat": 1.9293,
        "lon": 30.04919,
        "cases": 120,
        "deaths": 25,
        "recoveries": 3,
        "cfr": 20.8,
        "date": "2026-06-12"
    },
    {
        "hc_name": "Rwampara General Referral Hospital",
        "hc_type": "Ebola Treatment Center",
        "country": "DRC",
        "province": "Ituri",
        "zone": "Rwampara",
        "lat": 1.54348,
        "lon": 30.17918,
        "cases": 100,
        "deaths": 20,
        "recoveries": 2,
        "cfr": 20.0,
        "date": "2026-06-12"
    },
    {
        "hc_name": "Aru General Referral Hospital",
        "hc_type": "Ebola Treatment Center",
        "country": "DRC",
        "province": "Ituri",
        "zone": "Aru",
        "lat": 2.85902,
        "lon": 30.83841,
        "cases": 80,
        "deaths": 15,
        "recoveries": 1,
        "cfr": 18.8,
        "date": "2026-06-12"
    },
    {
        "hc_name": "Kasenye Treatment Center",
        "hc_type": "Ebola Treatment Center",
        "country": "DRC",
        "province": "Ituri",
        "zone": "Other Health Zones",
        "lat": 1.39197,
        "lon": 30.44024,
        "cases": 179,
        "deaths": 39,
        "recoveries": 1,
        "cfr": 21.8,
        "date": "2026-06-12"
    },
    {
        "hc_name": "Beni General Referral Hospital",
        "hc_type": "Ebola Treatment Center",
        "country": "DRC",
        "province": "North Kivu",
        "zone": "Beni",
        "lat": 0.4911,
        "lon": 29.4731,
        "cases": 44,
        "deaths": 10,
        "recoveries": 0,
        "cfr": 22.7,
        "date": "2026-06-12"
    },
    {
        "hc_name": "H\u00f4pital de l\u2019Amiti\u00e9 Sino-Congolaise",
        "hc_type": "Isolation Center",
        "country": "DRC",
        "province": "Kinshasa",
        "zone": "Kinshasa",
        "lat": -4.40334,
        "lon": 15.37416,
        "cases": 13,
        "deaths": 0,
        "recoveries": 0,
        "cfr": 0.0,
        "date": "2026-06-12"
    },
    {
        "hc_name": "Miti-Murhesa Health Center",
        "hc_type": "Isolation Center",
        "country": "DRC",
        "province": "South Kivu",
        "zone": "Miti-Murhesa",
        "lat": -2.3667,
        "lon": 28.8,
        "cases": 3,
        "deaths": 0,
        "recoveries": 0,
        "cfr": 0.0,
        "date": "2026-06-12"
    },
    {
        "hc_name": "Mulago National Referral Hospital",
        "hc_type": "Isolation Unit",
        "country": "Uganda",
        "province": "Central",
        "zone": "Kampala",
        "lat": 0.33779,
        "lon": 32.57555,
        "cases": 8,
        "deaths": 1,
        "recoveries": 3,
        "cfr": 12.5,
        "date": "2026-06-12"
    },
    {
        "hc_name": "Entebbe Regional Referral Hospital",
        "hc_type": "Isolation Unit",
        "country": "Uganda",
        "province": "Wakiso",
        "zone": "Wakiso",
        "lat": 0.06387,
        "lon": 32.47166,
        "cases": 1,
        "deaths": 0,
        "recoveries": 1,
        "cfr": 0.0,
        "date": "2026-06-12"
    },
    {
        "hc_name": "Bwera General Hospital",
        "hc_type": "Border Screening ETC",
        "country": "Uganda",
        "province": "Kasese",
        "zone": "Border Zones",
        "lat": 0.0333,
        "lon": 29.7667,
        "cases": 10,
        "deaths": 1,
        "recoveries": 1,
        "cfr": 10.0,
        "date": "2026-06-12"
    }
];